name: bgpq4
base: core18
version: git
summary: BGP filtering automation tool
description: |
  The bgpq4 utility used to generate configurations (prefix-lists, extended
  access-lists, policy-statement terms and as-path lists) based on IRR data.
website: https://github.com/bgp/bgpq4
source-code: https://github.com/bgp/bgpq4.git
issues: https://github.com/bgp/bgpq4/issues
license: BSD-2-Clause

grade: stable
confinement: strict

apps:
  bgpq4:
    command: bin/bgpq4
    plugs:
      - network

parts:
  bgpq4:
    plugin: autotools
    source: .
